---
# Ansible Inventory - Auto-generated by Terraform
# Do not edit manually - changes will be overwritten

all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ${ssh_key_file}
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    postgres_port: ${postgres_port}
    haproxy_postgres_port: ${haproxy_port}
    haproxy_stats_port: ${stats_port}

  children:
    postgres:
      hosts:
%{ for node in postgres_nodes ~}
        ${node.name}:
          ansible_host: ${node.public_ip}
          private_ip: ${node.private_ip}
          node_id: ${node.node_id}
%{ endfor ~}
      vars:
        repmgr_node_priority: 100

    haproxy:
      hosts:
        ${haproxy_node.name}-lb:
          ansible_host: ${haproxy_node.public_ip}
          private_ip: ${haproxy_node.private_ip}
